# -*- coding: utf-8 -*-
"""config.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DZS9oERQ8lXKB4FEZGVKBVTNRbANYKgS
"""

import torch
import os
import shutil
from google.colab import files

# Device configuration
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
NUM_WORKERS = 2 if DEVICE == "cuda" else 0
PIN_MEMORY = DEVICE == "cuda"

print(f"Using device: {DEVICE}")
if DEVICE == "cuda":
    print(f"GPU: {torch.cuda.get_device_name(0)}")

# Data paths
BASE_DIR = "/content/Data"

TRAIN_IMG_DIR = os.path.join(BASE_DIR, "train/image")
TRAIN_MASK_DIR = os.path.join(BASE_DIR, "train/mask")

VAL_IMG_DIR = os.path.join(BASE_DIR, "val/image")
VAL_MASK_DIR = os.path.join(BASE_DIR, "val/mask")

TEST_IMG_DIR = os.path.join(BASE_DIR, "test/image")
TEST_MASK_DIR = os.path.join(BASE_DIR, "test/mask")

# Output directories
MODEL_DIR = "/content/Models"
RESULTS_DIR = "/content/Results"
SCREENSHOTS_DIR = os.path.join(RESULTS_DIR, "screenshots")

for d in [MODEL_DIR, RESULTS_DIR, SCREENSHOTS_DIR]:
    os.makedirs(d, exist_ok=True)

SAVE_MODEL_PATH = os.path.join(MODEL_DIR, "best_model.pth")

# Model architecture
NUM_BLOCKS = 3
IN_CHANNELS = 3
OUT_CHANNELS = 1
DROPOUT = 0.1

# Data processing
IMAGE_HEIGHT = 256
IMAGE_WIDTH = 256
USE_NORMALIZATION = True

# Data augmentation
USE_AUGMENTATION = True
AUG_HORIZONTAL_FLIP = 0.5
AUG_VERTICAL_FLIP = 0.5
AUG_ROTATION_LIMIT = 15

# Training hyperparameters
BATCH_SIZE = 4
EPOCHS = 30
LEARNING_RATE = 1e-4
OPTIMIZER = "Adam"
WEIGHT_DECAY = 1e-5

# Loss
BCE_WEIGHT = 0.5
DICE_WEIGHT = 0.5
SMOOTH = 1e-6

# Scheduler and early stopping
USE_SCHEDULER = True
SCHEDULER_PATIENCE = 5
SCHEDULER_FACTOR = 0.5
USE_EARLY_STOPPING = True
EARLY_STOPPING_PATIENCE = 10

# Checkpointing
SAVE_EVERY = 5
SAVE_BEST_ONLY = True

# Testing
TEST_THRESHOLD = 0.5

# Configuration summary
def print_config():
    print("\n" + "=" * 60)
    print("Configuration Summary")
    print("=" * 60)
    print(f"Device:        {DEVICE}")
    print(f"Train Images:  {TRAIN_IMG_DIR}")
    print(f"Val Images:    {VAL_IMG_DIR}")
    print(f"Test Images:   {TEST_IMG_DIR}")
    print(f"Model Save To: {SAVE_MODEL_PATH}")
    print(f"Epochs:        {EPOCHS}")
    print(f"Batch Size:    {BATCH_SIZE}")
    print(f"Learning Rate: {LEARNING_RATE}")
    print(f"Optimizer:     {OPTIMIZER}")
    print(f"Dropout:       {DROPOUT}")
    print(f"Normalization: {USE_NORMALIZATION}")
    print("=" * 60 + "\n")


if __name__ == "__main__":
    print_config()

# Optional experiment settings
EXPERIMENT_CONFIGS = [
    {"name": "UNet2Block_WithNorm", "num_blocks": 2, "use_normalization": True},
    {"name": "UNet3Block_WithNorm", "num_blocks": 3, "use_normalization": True},
    {"name": "UNet3Block_NoNorm", "num_blocks": 3, "use_normalization": False}
]

# Create ZIP for download
def create_zip(output_name="submission.zip"):
    """
    Creates a zip file from all outputs (Models, Results) and
    lets you download it directly to your computer.
    """
    zip_path = f"/content/{output_name}"

    shutil.make_archive(zip_path.replace(".zip", ""), "zip", "/content", "Models")
    shutil.make_archive(zip_path.replace(".zip", "_results"), "zip", "/content", "Results")

    final_zip = f"/content/{output_name}"
    shutil.make_archive(final_zip.replace(".zip", ""), "zip", "/content")
    print(f"\nZIP file created at: {final_zip}")

    files.download(final_zip)
    print("Download started... check your browser's download bar.")