# -*- coding: utf-8 -*-
"""metrics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QVDv7rYEIrC-apZIOF-6vU1U2PQSmk9l
"""

import torch
import torch.nn as nn


def dice_score(pred, target, smooth=1e-6):
    """
    Calculates the Dice coefficient for binary segmentation.

    Args:
        pred: predicted mask (B, 1, H, W) - should already be passed through sigmoid
        target: ground truth mask (B, 1, H, W)
        smooth: small constant to avoid division by zero

    Returns:
        Mean Dice score between 0 and 1.
    """
    pred = pred.contiguous().view(pred.size(0), -1)
    target = target.contiguous().view(target.size(0), -1)

    intersection = (pred * target).sum(dim=1)
    dice = (2. * intersection + smooth) / (pred.sum(dim=1) + target.sum(dim=1) + smooth)

    return dice.mean().item()


def iou_score(pred, target, smooth=1e-6):
    """
    Calculates the Intersection over Union (IoU) for binary segmentation.

    Args:
        pred: predicted mask (B, 1, H, W) - should already be passed through sigmoid
        target: ground truth mask (B, 1, H, W)
        smooth: small constant to avoid division by zero

    Returns:
        Mean IoU score between 0 and 1.
    """
    pred = pred.contiguous().view(pred.size(0), -1)
    target = target.contiguous().view(target.size(0), -1)

    intersection = (pred * target).sum(dim=1)
    union = pred.sum(dim=1) + target.sum(dim=1) - intersection
    iou = (intersection + smooth) / (union + smooth)

    return iou.mean().item()


class DiceLoss(nn.Module):
    """
    Differentiable Dice loss for training.
    Assumes model output has already passed through sigmoid.

    Args:
        smooth: small constant for numerical stability (default: 1e-6)
    """
    def __init__(self, smooth=1e-6):
        super().__init__()
        self.smooth = smooth

    def forward(self, pred, target):
        """
        Args:
            pred: predicted probabilities (B, 1, H, W)
            target: ground truth binary mask (B, 1, H, W)

        Returns:
            Dice loss (scalar)
        """
        pred = pred.contiguous().view(pred.size(0), -1)
        target = target.contiguous().view(target.size(0), -1)

        intersection = (pred * target).sum(dim=1)
        dice = (2. * intersection + self.smooth) / (pred.sum(dim=1) + target.sum(dim=1) + self.smooth)

        return 1 - dice.mean()


class CombinedLoss(nn.Module):
    """
    Combination of Binary Cross-Entropy and Dice loss.
    Works better for imbalanced segmentation datasets.

    Args:
        bce_weight: weight for BCE loss (default: 0.5)
        dice_weight: weight for Dice loss (default: 0.5)
        smooth: smoothing constant for Dice loss (default: 1e-6)
    """
    def __init__(self, bce_weight=0.5, dice_weight=0.5, smooth=1e-6):
        super().__init__()
        self.bce_weight = bce_weight
        self.dice_weight = dice_weight
        self.bce = nn.BCELoss()
        self.dice = DiceLoss(smooth=smooth)

    def forward(self, pred, target):
        """
        Args:
            pred: predicted probabilities (B, 1, H, W)
            target: ground truth binary mask (B, 1, H, W)

        Returns:
            Combined loss (scalar)
        """
        bce_loss = self.bce(pred, target)
        dice_loss = self.dice(pred, target)
        return self.bce_weight * bce_loss + self.dice_weight * dice_loss


if __name__ == "__main__":
    print("=" * 70)
    print("Testing Metrics and Loss Functions")
    print("=" * 70)

    # Simulated data
    batch_size = 2
    y_pred = torch.sigmoid(torch.randn(batch_size, 1, 256, 256))
    y_true = torch.randint(0, 2, (batch_size, 1, 256, 256)).float()

    print("\n Evaluation Metrics ")
    dice = dice_score(y_pred, y_true)
    iou = iou_score(y_pred, y_true)
    print(f"Dice Score: {dice:.4f}")
    print(f"IoU Score : {iou:.4f}")

    print("\n Training Loss ")
    criterion = CombinedLoss(bce_weight=0.5, dice_weight=0.5)
    y_pred.requires_grad = True
    loss_val = criterion(y_pred, y_true)
    print(f"Combined Loss: {loss_val.item():.4f}")

    # Gradient check
    loss_val.backward()
    print(f"Gradient Check: {y_pred.grad is not None}")
    print(f"Gradient Stats: mean={y_pred.grad.mean():.6f}, std={y_pred.grad.std():.6f}")

    print("\n Perfect Prediction Test ")
    y_pred_perfect = y_true.clone()
    dice_perfect = dice_score(y_pred_perfect, y_true)
    iou_perfect = iou_score(y_pred_perfect, y_true)
    loss_perfect = criterion(y_pred_perfect, y_true)
    print(f"Dice Score: {dice_perfect:.6f} (expected ~1.0)")
    print(f"IoU Score : {iou_perfect:.6f} (expected ~1.0)")
    print(f"Loss      : {loss_perfect.item():.6f} (expected ~0.0)")

    print("\n Worst Prediction Test ")
    y_pred_worst = 1.0 - y_true
    dice_worst = dice_score(y_pred_worst, y_true)
    iou_worst = iou_score(y_pred_worst, y_true)
    loss_worst = criterion(y_pred_worst, y_true)
    print(f"Dice Score: {dice_worst:.6f} (expected ~0.0)")
    print(f"IoU Score : {iou_worst:.6f} (expected ~0.0)")
    print(f"Loss      : {loss_worst.item():.6f} (expected ~1.0)")

    print("\n" + "=" * 70)
    print("All tests passed!")
    print("=" * 70)