# -*- coding: utf-8 -*-
"""model_unet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JFJcn6obT_VRGvTwFM7DPIsY_Sk6Qt_r
"""

import torch
import torch.nn as nn


# Basic Conv Block
class ConvBlock(nn.Module):
    """Two-layer conv block with BatchNorm and optional Dropout."""
    def __init__(self, in_channels, out_channels, dropout=0.1):
        super(ConvBlock, self).__init__()
        self.conv = nn.Sequential(
            nn.Conv2d(in_channels, out_channels, kernel_size=3, padding=1),
            nn.BatchNorm2d(out_channels),
            nn.ReLU(inplace=True),
            nn.Dropout2d(dropout),
            nn.Conv2d(out_channels, out_channels, kernel_size=3, padding=1),
            nn.BatchNorm2d(out_channels),
            nn.ReLU(inplace=True)
        )

    def forward(self, x):
        return self.conv(x)


# U-Net 2-Block
class UNet2Block(nn.Module):
    """Compact U-Net with 2 encoder-decoder blocks."""
    def __init__(self, in_channels=3, out_channels=1, dropout=0.1):
        super(UNet2Block, self).__init__()

        # Encoder
        self.enc1 = ConvBlock(in_channels, 64, dropout)
        self.pool1 = nn.MaxPool2d(2)
        self.enc2 = ConvBlock(64, 128, dropout)
        self.pool2 = nn.MaxPool2d(2)

        # Bottleneck
        self.bottleneck = ConvBlock(128, 256, dropout)

        # Decoder
        self.up2 = nn.ConvTranspose2d(256, 128, kernel_size=2, stride=2)
        self.dec2 = ConvBlock(256, 128, dropout)

        self.up1 = nn.ConvTranspose2d(128, 64, kernel_size=2, stride=2)
        self.dec1 = ConvBlock(128, 64, dropout)

        # Output
        self.out_conv = nn.Conv2d(64, out_channels, kernel_size=1)

    def forward(self, x):
        e1 = self.enc1(x)
        p1 = self.pool1(e1)

        e2 = self.enc2(p1)
        p2 = self.pool2(e2)

        b = self.bottleneck(p2)

        up2 = self.up2(b)
        up2 = torch.cat([up2, e2], dim=1)
        d2 = self.dec2(up2)

        up1 = self.up1(d2)
        up1 = torch.cat([up1, e1], dim=1)
        d1 = self.dec1(up1)

        out = torch.sigmoid(self.out_conv(d1))
        return out


# U-Net 3-Block
class UNet3Block(nn.Module):
    """Deeper U-Net with 3 encoder-decoder blocks."""
    def __init__(self, in_channels=3, out_channels=1, dropout=0.1):
        super(UNet3Block, self).__init__()

        # Encoder
        self.enc1 = ConvBlock(in_channels, 64, dropout)
        self.pool1 = nn.MaxPool2d(2)
        self.enc2 = ConvBlock(64, 128, dropout)
        self.pool2 = nn.MaxPool2d(2)
        self.enc3 = ConvBlock(128, 256, dropout)
        self.pool3 = nn.MaxPool2d(2)

        # Bottleneck
        self.bottleneck = ConvBlock(256, 512, dropout)

        # Decoder
        self.up3 = nn.ConvTranspose2d(512, 256, kernel_size=2, stride=2)
        self.dec3 = ConvBlock(512, 256, dropout)

        self.up2 = nn.ConvTranspose2d(256, 128, kernel_size=2, stride=2)
        self.dec2 = ConvBlock(256, 128, dropout)

        self.up1 = nn.ConvTranspose2d(128, 64, kernel_size=2, stride=2)
        self.dec1 = ConvBlock(128, 64, dropout)

        self.out_conv = nn.Conv2d(64, out_channels, kernel_size=1)

    def forward(self, x):
        e1 = self.enc1(x)
        p1 = self.pool1(e1)

        e2 = self.enc2(p1)
        p2 = self.pool2(e2)

        e3 = self.enc3(p2)
        p3 = self.pool3(e3)

        b = self.bottleneck(p3)

        up3 = self.up3(b)
        up3 = torch.cat([up3, e3], dim=1)
        d3 = self.dec3(up3)

        up2 = self.up2(d3)
        up2 = torch.cat([up2, e2], dim=1)
        d2 = self.dec2(up2)

        up1 = self.up1(d2)
        up1 = torch.cat([up1, e1], dim=1)
        d1 = self.dec1(up1)

        out = torch.sigmoid(self.out_conv(d1))
        return out


# U-Net 4-Block
class UNet4Block(nn.Module):
    """Extended U-Net with 4 encoder-decoder blocks."""
    def __init__(self, in_channels=3, out_channels=1, dropout=0.1):
        super(UNet4Block, self).__init__()

        # Encoder
        self.enc1 = ConvBlock(in_channels, 64, dropout)
        self.pool1 = nn.MaxPool2d(2)
        self.enc2 = ConvBlock(64, 128, dropout)
        self.pool2 = nn.MaxPool2d(2)
        self.enc3 = ConvBlock(128, 256, dropout)
        self.pool3 = nn.MaxPool2d(2)
        self.enc4 = ConvBlock(256, 512, dropout)
        self.pool4 = nn.MaxPool2d(2)

        # Bottleneck
        self.bottleneck = ConvBlock(512, 1024, dropout)

        # Decoder
        self.up4 = nn.ConvTranspose2d(1024, 512, kernel_size=2, stride=2)
        self.dec4 = ConvBlock(1024, 512, dropout)

        self.up3 = nn.ConvTranspose2d(512, 256, kernel_size=2, stride=2)
        self.dec3 = ConvBlock(512, 256, dropout)

        self.up2 = nn.ConvTranspose2d(256, 128, kernel_size=2, stride=2)
        self.dec2 = ConvBlock(256, 128, dropout)

        self.up1 = nn.ConvTranspose2d(128, 64, kernel_size=2, stride=2)
        self.dec1 = ConvBlock(128, 64, dropout)

        self.out_conv = nn.Conv2d(64, out_channels, kernel_size=1)

    def forward(self, x):
        e1 = self.enc1(x)
        p1 = self.pool1(e1)

        e2 = self.enc2(p1)
        p2 = self.pool2(e2)

        e3 = self.enc3(p2)
        p3 = self.pool3(e3)

        e4 = self.enc4(p3)
        p4 = self.pool4(e4)

        b = self.bottleneck(p4)

        up4 = self.up4(b)
        up4 = torch.cat([up4, e4], dim=1)
        d4 = self.dec4(up4)

        up3 = self.up3(d4)
        up3 = torch.cat([up3, e3], dim=1)
        d3 = self.dec3(up3)

        up2 = self.up2(d3)
        up2 = torch.cat([up2, e2], dim=1)
        d2 = self.dec2(up2)

        up1 = self.up1(d2)
        up1 = torch.cat([up1, e1], dim=1)
        d1 = self.dec1(up1)

        out = torch.sigmoid(self.out_conv(d1))
        return out


# Factory Function
def get_unet_model(num_blocks=3, in_channels=3, out_channels=1, dropout=0.1):
    """
    Factory function to select U-Net model by number of blocks.

    Args:
        num_blocks: 2, 3, or 4
        in_channels: number of input channels (default: 3 for RGB)
        out_channels: number of output channels (default: 1 for binary mask)
        dropout: dropout rate (default: 0.1)

    Returns:
        U-Net model instance
    """
    models = {
        2: UNet2Block,
        3: UNet3Block,
        4: UNet4Block
    }

    if num_blocks not in models:
        raise ValueError(f"num_blocks must be 2, 3, or 4. Got {num_blocks}")

    return models[num_blocks](in_channels, out_channels, dropout)


# Quick Test
if __name__ == "__main__":
    print("="*70)
    print("U-Net Architecture Test")
    print("="*70)

    x = torch.randn(1, 3, 256, 256)

    models_dict = {
        "2-Block": UNet2Block(),
        "3-Block": UNet3Block(),
        "4-Block": UNet4Block()
    }

    print("\nOutput Shapes and Parameters:")
    print("-"*70)
    for name, model in models_dict.items():
        y = model(x)
        params = sum(p.numel() for p in model.parameters())
        print(f"{name:10s} -> Output: {str(y.shape):25s} Params: {params:,}")

    print("\n" + "-"*70)
    print("Factory Function Test:")
    print("-"*70)
    test_model = get_unet_model(num_blocks=3, dropout=0.1)
    test_output = test_model(x)
    print(f"get_unet_model(3) output shape: {test_output.shape}")
    print(f"Output value range: [{test_output.min():.4f}, {test_output.max():.4f}]")

    print("\n" + "="*70)
    print("All tests passed!")
    print("="*70)