# -*- coding: utf-8 -*-
"""trainer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IRr_yoeSqL8gn7p7ulGAYg-9S-AMSqQm
"""

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader
from tqdm import tqdm
import os
import matplotlib.pyplot as plt
import numpy as np
import albumentations as A
import shutil
from google.colab import files

import config
from model_unet import get_unet_model
from data_loader import RetinaDataset
from metrics import CombinedLoss, dice_score, iou_score


def create_dataloaders():
    """Create train, validation, and test dataloaders."""

    # Define augmentations for training
    if config.USE_AUGMENTATION:
        train_transform = A.Compose([
            A.HorizontalFlip(p=config.AUG_HORIZONTAL_FLIP),
            A.VerticalFlip(p=config.AUG_VERTICAL_FLIP),
            A.Rotate(limit=config.AUG_ROTATION_LIMIT, p=0.5),
        ])
    else:
        train_transform = None

    # Create datasets
    train_dataset = RetinaDataset(
        image_dir=config.TRAIN_IMG_DIR,
        mask_dir=config.TRAIN_MASK_DIR,
        image_size=(config.IMAGE_HEIGHT, config.IMAGE_WIDTH),
        transform=train_transform
    )

    val_dataset = RetinaDataset(
        image_dir=config.VAL_IMG_DIR,
        mask_dir=config.VAL_MASK_DIR,
        image_size=(config.IMAGE_HEIGHT, config.IMAGE_WIDTH),
        transform=None
    )

    test_dataset = RetinaDataset(
        image_dir=config.TEST_IMG_DIR,
        mask_dir=config.TEST_MASK_DIR,
        image_size=(config.IMAGE_HEIGHT, config.IMAGE_WIDTH),
        transform=None
    )

    # Create dataloaders
    train_loader = DataLoader(
        train_dataset,
        batch_size=config.BATCH_SIZE,
        shuffle=True,
        num_workers=config.NUM_WORKERS,
        pin_memory=config.PIN_MEMORY
    )

    val_loader = DataLoader(
        val_dataset,
        batch_size=config.BATCH_SIZE,
        shuffle=False,
        num_workers=config.NUM_WORKERS,
        pin_memory=config.PIN_MEMORY
    )

    test_loader = DataLoader(
        test_dataset,
        batch_size=1,
        shuffle=False,
        num_workers=config.NUM_WORKERS,
        pin_memory=config.PIN_MEMORY
    )

    print(f"Train samples: {len(train_dataset)}")
    print(f"Val samples  : {len(val_dataset)}")
    print(f"Test samples : {len(test_dataset)}")

    return train_loader, val_loader, test_loader


def train_one_epoch(model, dataloader, criterion, optimizer, device):
    """Train for one epoch."""
    model.train()

    running_loss = 0.0
    running_dice = 0.0
    running_iou = 0.0

    pbar = tqdm(dataloader, desc="Training")

    for batch_idx, (images, masks) in enumerate(pbar):
        images = images.to(device)
        masks = masks.to(device)

        # Forward pass
        optimizer.zero_grad()
        outputs = model(images)
        loss = criterion(outputs, masks)

        # Backward pass
        loss.backward()
        optimizer.step()

        # Calculate metrics
        with torch.no_grad():
            dice = dice_score(outputs, masks)
            iou = iou_score(outputs, masks)

        # Update running metrics
        running_loss += loss.item()
        running_dice += dice
        running_iou += iou

        # Update progress bar
        pbar.set_postfix({
            'loss': f'{loss.item():.4f}',
            'dice': f'{dice:.4f}',
            'iou': f'{iou:.4f}'
        })

    # Calculate epoch metrics
    epoch_loss = running_loss / len(dataloader)
    epoch_dice = running_dice / len(dataloader)
    epoch_iou = running_iou / len(dataloader)

    return epoch_loss, epoch_dice, epoch_iou


def validate(model, dataloader, criterion, device):
    """Validate the model."""
    model.eval()

    running_loss = 0.0
    running_dice = 0.0
    running_iou = 0.0

    with torch.no_grad():
        pbar = tqdm(dataloader, desc="Validation")

        for images, masks in pbar:
            images = images.to(device)
            masks = masks.to(device)

            # Forward pass
            outputs = model(images)
            loss = criterion(outputs, masks)

            # Calculate metrics
            dice = dice_score(outputs, masks)
            iou = iou_score(outputs, masks)

            # Update running metrics
            running_loss += loss.item()
            running_dice += dice
            running_iou += iou

            # Update progress bar
            pbar.set_postfix({
                'loss': f'{loss.item():.4f}',
                'dice': f'{dice:.4f}',
                'iou': f'{iou:.4f}'
            })

    # Calculate epoch metrics
    epoch_loss = running_loss / len(dataloader)
    epoch_dice = running_dice / len(dataloader)
    epoch_iou = running_iou / len(dataloader)

    return epoch_loss, epoch_dice, epoch_iou


def plot_metrics(train_losses, val_losses, train_dice, val_dice, train_iou, val_iou, save_path):
    """Plot and save training metrics."""
    fig, axes = plt.subplots(1, 3, figsize=(18, 5))

    # Plot loss
    axes[0].plot(train_losses, label='Train Loss', marker='o')
    axes[0].plot(val_losses, label='Val Loss', marker='s')
    axes[0].set_xlabel('Epoch')
    axes[0].set_ylabel('Loss')
    axes[0].set_title('Training and Validation Loss')
    axes[0].legend()
    axes[0].grid(True)

    # Plot Dice score
    axes[1].plot(train_dice, label='Train Dice', marker='o')
    axes[1].plot(val_dice, label='Val Dice', marker='s')
    axes[1].set_xlabel('Epoch')
    axes[1].set_ylabel('Dice Score')
    axes[1].set_title('Training and Validation Dice Score')
    axes[1].legend()
    axes[1].grid(True)

    # Plot IoU score
    axes[2].plot(train_iou, label='Train IoU', marker='o')
    axes[2].plot(val_iou, label='Val IoU', marker='s')
    axes[2].set_xlabel('Epoch')
    axes[2].set_ylabel('IoU Score')
    axes[2].set_title('Training and Validation IoU Score')
    axes[2].legend()
    axes[2].grid(True)

    plt.tight_layout()
    plt.savefig(save_path, dpi=150, bbox_inches='tight')
    plt.close(fig)
    print(f"Metrics plot saved to {save_path}")


def train_model(model_name="best_model"):
    """Main training function."""

    print("=" * 70)
    print("Starting Training")
    print("=" * 70)

    # Print configuration
    config.print_config()

    # Setup device
    device = torch.device(config.DEVICE)
    print(f"\nUsing device: {device}\n")

    # Create dataloaders
    print("Creating dataloaders...")
    train_loader, val_loader, test_loader = create_dataloaders()

    # Create model
    print(f"\nCreating U-Net {config.NUM_BLOCKS}-Block model...")
    model = get_unet_model(
        num_blocks=config.NUM_BLOCKS,
        in_channels=config.IN_CHANNELS,
        out_channels=config.OUT_CHANNELS,
        dropout=config.DROPOUT
    )
    model = model.to(device)

    # Count parameters
    total_params = sum(p.numel() for p in model.parameters())
    print(f"Total parameters: {total_params:,}")

    # Define loss function
    criterion = CombinedLoss(
        bce_weight=config.BCE_WEIGHT,
        dice_weight=config.DICE_WEIGHT,
        smooth=config.SMOOTH
    )

    # Define optimizer
    if config.OPTIMIZER == "Adam":
        optimizer = optim.Adam(
            model.parameters(),
            lr=config.LEARNING_RATE,
            weight_decay=config.WEIGHT_DECAY
        )
    elif config.OPTIMIZER == "AdamW":
        optimizer = optim.AdamW(
            model.parameters(),
            lr=config.LEARNING_RATE,
            weight_decay=config.WEIGHT_DECAY
        )
    else:
        optimizer = optim.SGD(
            model.parameters(),
            lr=config.LEARNING_RATE,
            momentum=0.9,
            weight_decay=config.WEIGHT_DECAY
        )

    # Define learning rate scheduler
    if config.USE_SCHEDULER:
        scheduler = optim.lr_scheduler.ReduceLROnPlateau(
            optimizer,
            mode='min',
            factor=config.SCHEDULER_FACTOR,
            patience=config.SCHEDULER_PATIENCE,
        )

    # Training history
    history = {
        'train_loss': [],
        'val_loss': [],
        'train_dice': [],
        'val_dice': [],
        'train_iou': [],
        'val_iou': []
    }

    # Early stopping
    best_val_dice = 0.0
    patience_counter = 0

    # Training loop
    print("\n" + "=" * 70)
    print("Starting Training Loop")
    print("=" * 70 + "\n")

    for epoch in range(1, config.EPOCHS + 1):
        print(f"\nEpoch {epoch}/{config.EPOCHS}")
        print("-" * 70)

        # Train
        train_loss, train_dice, train_iou = train_one_epoch(
            model, train_loader, criterion, optimizer, device
        )

        # Validate
        val_loss, val_dice, val_iou = validate(
            model, val_loader, criterion, device
        )

        # Update history
        history['train_loss'].append(train_loss)
        history['val_loss'].append(val_loss)
        history['train_dice'].append(train_dice)
        history['val_dice'].append(val_dice)
        history['train_iou'].append(train_iou)
        history['val_iou'].append(val_iou)

        # Print epoch summary
        print(f"\nEpoch {epoch} Summary:")
        print(f"  Train Loss: {train_loss:.4f} | Val Loss: {val_loss:.4f}")
        print(f"  Train Dice: {train_dice:.4f} | Val Dice: {val_dice:.4f}")
        print(f"  Train IoU : {train_iou:.4f} | Val IoU : {val_iou:.4f}")

        # Learning rate scheduler
        if config.USE_SCHEDULER:
            scheduler.step(val_loss)
            current_lr = optimizer.param_groups[0]['lr']
            print(f"  Learning Rate: {current_lr:.2e}")

        # Save best model
        if val_dice > best_val_dice:
            best_val_dice = val_dice
            patience_counter = 0

            save_path = os.path.join(config.MODEL_DIR, f"{model_name}.pth")
            torch.save({
                'epoch': epoch,
                'model_state_dict': model.state_dict(),
                'optimizer_state_dict': optimizer.state_dict(),
                'val_dice': val_dice,
                'val_iou': val_iou,
                'history': history
            }, save_path)
            print(f"  Best model saved! (Dice: {val_dice:.4f})")
        else:
            patience_counter += 1

        # Early stopping
        if config.USE_EARLY_STOPPING and patience_counter >= config.EARLY_STOPPING_PATIENCE:
            print(f"\nEarly stopping triggered after {epoch} epochs")
            break

        # Save checkpoint
        if epoch % config.SAVE_EVERY == 0:
            checkpoint_path = os.path.join(config.MODEL_DIR, f"{model_name}_epoch{epoch}.pth")
            torch.save({
                'epoch': epoch,
                'model_state_dict': model.state_dict(),
                'optimizer_state_dict': optimizer.state_dict(),
                'history': history
            }, checkpoint_path)
            print(f"  Checkpoint saved: epoch {epoch}")

    # Plot and save metrics
    print("\n" + "=" * 70)
    print("Training Complete!")
    print("=" * 70)
    print(f"Best Validation Dice: {best_val_dice:.4f}")

    plot_path = os.path.join(config.SCREENSHOTS_DIR, f"{model_name}_training_metrics.png")
    plot_metrics(
        history['train_loss'],
        history['val_loss'],
        history['train_dice'],
        history['val_dice'],
        history['train_iou'],
        history['val_iou'],
        plot_path
    )

    return model, history


def main():
    """Main entry point with training and automatic download."""

    # Train the model
    train_model(model_name="best_model")

    # Prepare files for download
    print("\n" + "=" * 70)
    print("Preparing files for download...")
    print("=" * 70)

    # Create organized structure
    output_dir = "/content/hw3_submission"
    os.makedirs(output_dir, exist_ok=True)

    # Copy Models folder
    if os.path.exists(config.MODEL_DIR):
        shutil.copytree(config.MODEL_DIR,
                       os.path.join(output_dir, "Models"),
                       dirs_exist_ok=True)
        print("Models folder copied")

    # Copy Results folder
    if os.path.exists(config.RESULTS_DIR):
        shutil.copytree(config.RESULTS_DIR,
                       os.path.join(output_dir, "Results"),
                       dirs_exist_ok=True)
        print("Results folder copied")

    # Create ZIP
    zip_base = "/content/iman_jamshidi_hw3_outputs"

    # Remove old ZIP if exists
    if os.path.exists(f"{zip_base}.zip"):
        os.remove(f"{zip_base}.zip")
        print("Old ZIP file removed")

    print(f"\nCreating ZIP file...")
    shutil.make_archive(zip_base, 'zip', output_dir)

    # Download ZIP
    zip_file = f"{zip_base}.zip"
    print(f"Downloading {zip_file}...")
    files.download(zip_file)

    print("\n" + "=" * 70)
    print("Download complete! Check your browser's Downloads folder.")
    print("=" * 70)


if __name__ == "__main__":
    main()